name: Documentation

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Asciidoctor
        run: |
          sudo apt-get update
          sudo apt-get install -y asciidoctor ruby-asciidoctor-pdf
          
      - name: Create dist directory
        run: mkdir -p dist
          
      - name: Build PDF
        run: |
          asciidoctor-pdf src/index.adoc -o dist/documentation.pdf
          
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: documentation-pdf
          path: dist/documentation.pdf
          retention-days: 90